apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beyblade-mongodb-pvc
  namespace: {{ .Values.namespace}}
  labels:
    app: beyblade-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ index .Values.mongo.storage_class_name (printf "%s" .Values.deployment) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: beyblade-mongodb-root-credentials
  namespace: {{ .Values.namespace}}
type: Opaque
data:
  username: {{ .Values.mongo.env.secret.mongo_initdb_username }}
  password: {{ .Values.mongo.env.secret.mongo_initdb_password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: beyblade-mongodb-beyblade-credentials
  namespace: {{ .Values.namespace}}
type: Opaque
data:
  username: {{ .Values.mongo.env.secret.BEYBLADE_db_username }}
  password: {{ .Values.mongo.env.secret.BEYBLADE_db_password }}
---
{{- if eq .Values.deployment "minikube" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubernetes-pv
  namespace: {{ .Values.namespace}}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubernetes_pv/"
{{- end}}